# サイト本体のビルド設定
[build]
  command = "ng build"
  publish = "dist/tetris-typed-game/browser"

# Functions (APIサーバー) の設定
[functions]
  # APIのコードが置かれているディレクトリ
  directory = "netlify/functions"

# リダイレクト設定 (変更なし)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
